apiVersion: v1
kind: Service
metadata:
  name: myworkflow
  namespace: namespace-workflow-1701512338782
spec:
  type: LoadBalancer
  selector:
    app: myworkflow
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000